[package]
name = "cargo-fuzz"
version = "0.4.1"
authors = ["The rust-fuzz Project Developers"]
license = "MIT OR Apache-2.0"
description = "Simple wrapper around libFuzzer"
repository = "https://github.com/rust-fuzz/cargo-fuzz/"

[dependencies]
toml            = "0.3"
term            = "0.4"
clap            = "2.21.1"
error-chain     = "0.10"

[workspace]
members = ["."]
