[package]
name = "cargo-fuzz"
version = "0.11.0"
authors = ["The rust-fuzz Project Developers"]
license = "MIT OR Apache-2.0"
description = "A `cargo` subcommand for fuzzing with `libFuzzer`! Easy to use!"
readme = "README.md"
repository = "https://github.com/rust-fuzz/cargo-fuzz/"
categories = ["development-tools::testing"]
edition = "2021"

[dependencies]
anyhow = "1.0.25"
current_platform = "0.2.0"
structopt = "0.3.5"
tempfile = "3.1.0"
toml = "0.5.5"
cargo-binutils = "0.3.3"

[workspace]
members = ["."]

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.2"
