[package]
name = "cargo-fuzz"
version = "0.7.4"
authors = ["The rust-fuzz Project Developers"]
license = "MIT OR Apache-2.0"
description = "A `cargo` subcommand for using `libFuzzer`! Easy to use! No need to recompile LLVM!"
readme = "README.md"
repository = "https://github.com/rust-fuzz/cargo-fuzz/"
categories = ["development-tools::testing"]
edition = "2018"

[dependencies]
anyhow = "1.0.25"
structopt = "0.3.5"
tempfile = "3.1.0"
toml = "0.5.5"

[workspace]
members = ["."]

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.2"
